spring:
  application:
    name: CATEGORYSERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/sweetcart
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
